Assignment 7
ThomasdenH/YieldMentorship pull request #5
Opened 2022-05-30 19:28 UTC by ThomasdenH

My submission for Assignment 7, the AMM! https://github.com/yieldprotocol/mentorship2022/issues/7

2022-06-01 09:15 UTC, alcueca requested changes
I found the math a bit confusing, due to using algebraic variable names, but kudos on detailing the formulas on the comments.

2022-06-01 09:15 UTC, alcueca commented on Assignment 7/src/Market.sol
> +        uint256 amount2
These would be clearer if they would be `xAmount` and `yAmount`

2022-06-01 09:15 UTC, alcueca commented on Assignment 7/src/Market.sol
> +    ///     will also determine the intial price: `x` of token X and `y` of
typo: initial

2022-06-01 09:15 UTC, alcueca commented on Assignment 7/src/Market.sol
> +    ///     token Y should have equal value. This function can only be called
Not necessarily, you can initialize with any amount of x and y, the market will find their relative values.

2022-06-01 09:15 UTC, alcueca commented on Assignment 7/src/Market.sol
> +                z = x * y0;
Isn't `z == zY`? Are you rounding on purpose?

2022-06-01 09:15 UTC, alcueca commented on Assignment 7/src/Market.sol
> +                z = y * x0;
`z = zX`?

2022-06-01 09:15 UTC, alcueca commented on Assignment 7/src/Market.sol
> +        tokenY.safeTransferFrom(msg.sender, address(this), y);
You could take here only the tokens needed.

2022-06-01 09:15 UTC, alcueca commented on Assignment 7/src/Market.sol
> +        //        = y0 * x / (x0 + x)
Hold on, `y0 - x0 * y0 == y0 * x`?

2022-06-01 09:15 UTC, alcueca commented on Assignment 7/test/Market.t.sol
> +        // tokens.
The invariant is that `k` is equal to the product of the reserves, and stays constant or increases with each trade. `k` is not equal to `totalSupply` except on initialization. `k != z`.

2022-06-01 12:36 UTC, ThomasdenH commented on Assignment 7/src/Market.sol
> +                z = x * y0;
Yeah, that was my idea. Giving out slightly too many liquidity tokens could mean that you would be able to take out more underlying tokens than you would be entitled to. Doing it repeatedly might be an attack vector? However, if you think it's a non-issue I'd rather reuse `zY`.

2022-06-01 12:44 UTC, ThomasdenH commented on Assignment 7/src/Market.sol
> +        tokenY.safeTransferFrom(msg.sender, address(this), y);
I might not understand what you mean. I already recompute `x` or `y` so that - rounding aside - `z/z0 = x/x0 = y/y0`.

2022-06-01 12:49 UTC, ThomasdenH commented on Assignment 7/src/Market.sol
> +        //        = y0 * x / (x0 + x)
I've written this in a bit of a confusing way. I've updated it as follows:
```
y = y0 - (x0 * y0 / (x0 + x))
   = (y0 * x0 + y0 * x - x0 * y0) / (x0 + x)
   = y0 * x / (x0 + x)
```

2022-06-01 12:51 UTC, ThomasdenH commented on Assignment 7/test/Market.t.sol
> +        // tokens.
Oof. I'll add more tests so that this is covered by them.

2022-06-02 14:11 UTC, ThomasdenH commented
I updated the contract and tests in accordance with the suggestions. I thought the invariant `k = x * y` was equal to `totalSupply()` and used that in the derivation of the maths. I therefore rewrote most of the calculations and derivation. I think it's much easier to understand now, if only for the fact that the calculations are much more straightforward.

As for tests, I added tests for events and errors, which I hadn't yet. Furthermore, I added tests that might have caught my wrong assumption by selling tokens after minting more liquidity (thereby breaking the assumption that `z=k`).

2022-06-03 15:03 UTC, alcueca approved these changes
Two minor corrections, that don't subtract from the good work, really.

In terms of variable naming, I was discussing about a standard with @devtooligan this morning, we came up with:

Variable names that refer to contracts are in the form: `xyzToken`. Examples: xToken, yvToken, sharesToken.
In some rare cases an extra word will be needed: yvDaiToken if the contract also has a yvUsdcToken.
Token amounts will be referred as the contract variable, without `Token`, plus a word denoting what happens with the token. In and Out will be the preferred words to denote tokens being transferred into the contract, or out of the contract. Examples: xIn, yOut, sharesMinted, yvDaiReceived.

2022-06-03 15:03 UTC, alcueca commented on Assignment 7/src/Market.sol
> +        emit Initialized(msg.sender, x, y);
It's customary to emit events at the end of a function. `z` might be useful in the event as well.

2022-06-03 15:03 UTC, alcueca commented on Assignment 7/src/Market.sol
> +        z = x * y;
If a user sends only `x` or `y` the effect will be a bit funny. The only impact is that an Initialized event will be emitted, without the contract actually being initialized. The user will lose some tokens, but that's from its own hand. I would probably put a `require` since you do it for `mint` as well.

2022-06-07 16:44 UTC, merged